# Generated by Django 3.0.2 on 2020-03-16 18:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='member_record',
            fields=[
                ('mid', models.AutoField(primary_key=True, serialize=False)),
                ('uname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=70)),
                ('last_name', models.CharField(max_length=70)),
                ('password', models.CharField(max_length=100)),
                ('repeat_password', models.CharField(max_length=100)),
                ('mobile_no', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=100)),
                ('amount', models.IntegerField(null=True)),
                ('profile_pic', models.ImageField(upload_to='Profileimage')),
                ('facebook', models.URLField()),
                ('twitter', models.URLField()),
                ('linkedin', models.URLField()),
                ('instagram', models.URLField()),
                ('join_date', models.DateTimeField(auto_now_add=True)),
                ('last_date', models.DateTimeField(default=datetime.datetime(2020, 4, 15, 18, 13, 57, 831073), null=True)),
                ('remaining_days', models.IntegerField(null=True)),
                ('payment_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='membership',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('membership_type', models.CharField(choices=[('Premirer', 'pre'), ('Popular', 'pop'), ('Basic', 'basic')], default='Free', max_length=30)),
                ('feature1', models.CharField(max_length=200)),
                ('feature2', models.CharField(max_length=200)),
                ('feature3', models.CharField(max_length=200)),
                ('feature4', models.CharField(max_length=200)),
                ('price', models.IntegerField(default=15)),
            ],
        ),
        migrations.CreateModel(
            name='subscription',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=False)),
                ('user_member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='videosub.member_record')),
            ],
        ),
        migrations.AddField(
            model_name='member_record',
            name='membership',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='videosub.membership'),
        ),
    ]
