# Generated by Django 3.0.2 on 2020-03-16 18:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videosub', '0004_auto_20200316_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member_record',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 15, 18, 19, 43, 662997), null=True),
        ),
    ]
