# Generated by Django 3.0.2 on 2020-03-20 11:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videosub', '0008_auto_20200319_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member_record',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 20, 11, 50, 49, 880805)),
        ),
        migrations.AlterField(
            model_name='member_record',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 19, 11, 50, 49, 880835), null=True),
        ),
    ]
