# Generated by Django 3.0.2 on 2020-03-20 13:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videosub', '0012_auto_20200320_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member_record',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 20, 13, 19, 31, 973706)),
        ),
        migrations.AlterField(
            model_name='member_record',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 19, 13, 19, 31, 973733), null=True),
        ),
    ]
