# Generated by Django 3.0.2 on 2020-04-24 19:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videosub', '0052_auto_20200424_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='feature4',
        ),
        migrations.AlterField(
            model_name='member_record',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 24, 19, 57, 31, 188928)),
        ),
        migrations.AlterField(
            model_name='member_record',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 24, 19, 57, 31, 188981), null=True),
        ),
    ]
