# Generated by Django 3.0.2 on 2020-04-24 23:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videosub', '0053_auto_20200424_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member_record',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 24, 23, 1, 28, 511128)),
        ),
        migrations.AlterField(
            model_name='member_record',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 24, 23, 1, 28, 511155), null=True),
        ),
        migrations.AlterField(
            model_name='member_record',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='Profileimage'),
        ),
    ]
