# Generated by Django 3.0.2 on 2020-04-24 23:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videosub', '0055_auto_20200424_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member_record',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 24, 23, 38, 12, 987720)),
        ),
        migrations.AlterField(
            model_name='member_record',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 24, 23, 38, 12, 987748), null=True),
        ),
        migrations.AlterField(
            model_name='member_record',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='Profileimage'),
        ),
    ]
