# Generated by Django 3.0.2 on 2020-04-26 00:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videosub', '0057_auto_20200425_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member_record',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='member_record',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 26, 0, 40, 48, 680783)),
        ),
        migrations.AlterField(
            model_name='member_record',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 26, 0, 40, 48, 680825), null=True),
        ),
    ]
