# Generated by Django 3.0.2 on 2020-04-26 15:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videosub', '0060_auto_20200426_1441'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='renewmembership',
            new_name='renewmember',
        ),
        migrations.AlterField(
            model_name='member_record',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 26, 15, 11, 17, 875180)),
        ),
        migrations.AlterField(
            model_name='member_record',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 26, 15, 11, 17, 875208), null=True),
        ),
    ]
