# Generated by Django 3.0.2 on 2020-04-27 10:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videosub', '0061_auto_20200426_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='member_record',
            name='favourite_movie',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member_record',
            name='favourite_webseries',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='member_record',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 27, 10, 29, 11, 692430)),
        ),
        migrations.AlterField(
            model_name='member_record',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 27, 10, 29, 11, 692457), null=True),
        ),
    ]
