# Generated by Django 3.0.2 on 2020-04-27 14:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videosub', '0062_auto_20200427_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member_record',
            name='amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='member_record',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 27, 14, 33, 44, 964811)),
        ),
        migrations.AlterField(
            model_name='member_record',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 27, 14, 33, 44, 964837), null=True),
        ),
        migrations.AlterField(
            model_name='renewmember',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.FloatField(),
        ),
    ]
