# Generated by Django 3.0.2 on 2020-04-30 10:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videosub', '0067_auto_20200429_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='member_record',
            name='member_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 30, 10, 43, 57, 121346)),
        ),
        migrations.AlterField(
            model_name='member_record',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 30, 10, 43, 57, 121386)),
        ),
        migrations.AlterField(
            model_name='member_record',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 30, 10, 43, 57, 121408), null=True),
        ),
    ]
