# Generated by Django 3.0.2 on 2020-03-16 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='main_catagory',
            fields=[
                ('main_id', models.AutoField(primary_key=True, serialize=False)),
                ('main_catagory', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='register_admin',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=70)),
                ('last_name', models.CharField(max_length=70)),
                ('password', models.CharField(max_length=256)),
                ('mobile_no', models.CharField(max_length=10)),
                ('profile_pic', models.ImageField(upload_to='AdminProfile')),
                ('join_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='sub_catagory',
            fields=[
                ('sub_id', models.AutoField(primary_key=True, serialize=False)),
                ('sub_catagory', models.CharField(max_length=150)),
                ('main_catagory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='NP_admin.main_catagory')),
            ],
        ),
        migrations.CreateModel(
            name='type_catagory',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_catagory', models.CharField(max_length=150)),
                ('main_catagory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='NP_admin.main_catagory')),
                ('sub_catagory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='NP_admin.sub_catagory')),
            ],
        ),
        migrations.CreateModel(
            name='movie_content',
            fields=[
                ('movie_id', models.AutoField(primary_key=True, serialize=False)),
                ('movie_name', models.CharField(max_length=100)),
                ('duration_hours', models.IntegerField()),
                ('duration_minutes', models.IntegerField()),
                ('release_date', models.DateField()),
                ('language', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('movie_trailer_thumbnail', models.ImageField(upload_to='movie_trailers_thumbnail')),
                ('movie_trailer', models.FileField(upload_to='movie_trailers')),
                ('movie_thumbnail', models.ImageField(upload_to='movie_thumbnail')),
                ('movie_576p', models.FileField(upload_to='movie_576p')),
                ('movie_720p', models.FileField(upload_to='movie_720p')),
                ('movie_1080p', models.FileField(upload_to='movie_1080p')),
                ('movie_bgimage', models.ImageField(upload_to='movie_background')),
                ('main_catagory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='NP_admin.main_catagory')),
                ('sub_catagory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='NP_admin.sub_catagory')),
                ('type_catagory1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type_cat1', to='NP_admin.type_catagory')),
                ('type_catagory2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type_cat2', to='NP_admin.type_catagory')),
                ('type_catagory3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type_cat3', to='NP_admin.type_catagory')),
                ('type_catagory4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type_cat4', to='NP_admin.type_catagory')),
                ('type_catagory5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type_cat5', to='NP_admin.type_catagory')),
            ],
        ),
    ]
