# Generated by Django 3.0.2 on 2020-03-16 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NP_admin', '0003_auto_20200316_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_content',
            name='movie_1080p',
            field=models.FileField(null=True, upload_to='movie_1080p'),
        ),
        migrations.AlterField(
            model_name='movie_content',
            name='movie_576p',
            field=models.FileField(null=True, upload_to='movie_576p'),
        ),
        migrations.AlterField(
            model_name='movie_content',
            name='movie_720p',
            field=models.FileField(null=True, upload_to='movie_720p'),
        ),
        migrations.AlterField(
            model_name='movie_content',
            name='movie_bgimage',
            field=models.ImageField(null=True, upload_to='movie_background'),
        ),
        migrations.AlterField(
            model_name='movie_content',
            name='movie_thumbnail',
            field=models.ImageField(null=True, upload_to='movie_thumbnail'),
        ),
        migrations.AlterField(
            model_name='movie_content',
            name='movie_trailer',
            field=models.FileField(null=True, upload_to='movie_trailers'),
        ),
        migrations.AlterField(
            model_name='movie_content',
            name='movie_trailer_thumbnail',
            field=models.ImageField(null=True, upload_to='movie_trailers_thumbnail'),
        ),
    ]
