# Generated by Django 3.0.2 on 2020-03-18 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NP_admin', '0004_auto_20200316_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='main_catagory',
            name='main_cat_image',
            field=models.ImageField(null=True, upload_to='main_cat_image'),
        ),
        migrations.AddField(
            model_name='sub_catagory',
            name='sub_cat_image',
            field=models.ImageField(null=True, upload_to='sub_cat_image'),
        ),
        migrations.AddField(
            model_name='type_catagory',
            name='type_cat_image',
            field=models.ImageField(null=True, upload_to='type_cat_image'),
        ),
    ]
