# Generated by Django 3.0.2 on 2020-03-18 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NP_admin', '0005_auto_20200318_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie_content',
            name='type_catagory2',
        ),
        migrations.RemoveField(
            model_name='movie_content',
            name='type_catagory3',
        ),
        migrations.RemoveField(
            model_name='movie_content',
            name='type_catagory4',
        ),
        migrations.RemoveField(
            model_name='movie_content',
            name='type_catagory5',
        ),
    ]
