# Generated by Django 3.0.2 on 2020-03-19 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NP_admin', '0006_auto_20200318_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_content',
            name='description',
            field=models.CharField(max_length=1500),
        ),
    ]
