# Generated by Django 3.0.2 on 2020-03-20 12:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NP_admin', '0010_auto_20200320_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_content',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 20, 12, 31, 49, 639919)),
        ),
    ]
