# Generated by Django 3.0.2 on 2020-03-20 13:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NP_admin', '0012_auto_20200320_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie_content',
            name='movie_trailer',
        ),
        migrations.AddField(
            model_name='movie_content',
            name='movie_trailer_1080p',
            field=models.FileField(null=True, upload_to='movie_trailers_1080p'),
        ),
        migrations.AddField(
            model_name='movie_content',
            name='movie_trailer_576p',
            field=models.FileField(null=True, upload_to='movie_trailers_576p'),
        ),
        migrations.AddField(
            model_name='movie_content',
            name='movie_trailer_720p',
            field=models.FileField(null=True, upload_to='movie_trailers_720p'),
        ),
        migrations.AlterField(
            model_name='movie_content',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 20, 13, 30, 20, 853192)),
        ),
    ]
