# Generated by Django 3.0.2 on 2020-03-20 13:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NP_admin', '0013_auto_20200320_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie_content',
            name='movie_portrait',
        ),
        migrations.AddField(
            model_name='movie_content',
            name='movie_poster',
            field=models.ImageField(null=True, upload_to='movie_poster'),
        ),
        migrations.AlterField(
            model_name='movie_content',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 20, 13, 41, 49, 492669)),
        ),
    ]
