# Generated by Django 3.0.2 on 2020-04-13 11:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NP_admin', '0014_auto_20200320_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='web_main_catagory',
            fields=[
                ('web_main_id', models.AutoField(primary_key=True, serialize=False)),
                ('main_catagory', models.CharField(max_length=150)),
                ('main_cat_image', models.ImageField(null=True, upload_to='web_main_cat_image')),
            ],
        ),
        migrations.CreateModel(
            name='web_sub_catagory',
            fields=[
                ('web_sub_id', models.AutoField(primary_key=True, serialize=False)),
                ('sub_catagory', models.CharField(max_length=150)),
                ('sub_cat_image', models.ImageField(null=True, upload_to='web_sub_cat_image')),
                ('main_catagory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='NP_admin.web_main_catagory')),
            ],
        ),
        migrations.AlterField(
            model_name='movie_content',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 13, 11, 38, 14, 392165)),
        ),
        migrations.AlterField(
            model_name='movie_content',
            name='movie_poster',
            field=models.ImageField(blank=True, null=True, upload_to='movie_poster'),
        ),
        migrations.CreateModel(
            name='web_type_catagory',
            fields=[
                ('web_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_catagory', models.CharField(max_length=150)),
                ('type_cat_image', models.ImageField(null=True, upload_to='web_type_cat_image')),
                ('main_catagory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='NP_admin.web_main_catagory')),
                ('sub_catagory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='NP_admin.web_sub_catagory')),
            ],
        ),
    ]
