# Generated by Django 3.0.2 on 2020-04-16 15:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NP_admin', '0017_auto_20200415_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webseries_content',
            name='season',
        ),
        migrations.RemoveField(
            model_name='webseries_content',
            name='season_name',
        ),
        migrations.RemoveField(
            model_name='webseries_content',
            name='webseries_session_poster',
        ),
        migrations.AlterField(
            model_name='movie_content',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 16, 15, 45, 58, 202338)),
        ),
        migrations.AlterField(
            model_name='webseries_content',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 16, 15, 45, 58, 203407)),
        ),
        migrations.CreateModel(
            name='webseries_season',
            fields=[
                ('webseries_season_id', models.AutoField(primary_key=True, serialize=False)),
                ('season_name', models.CharField(max_length=100)),
                ('duration_hours', models.IntegerField()),
                ('duration_minutes', models.IntegerField()),
                ('release_date', models.DateField()),
                ('season', models.CharField(max_length=20)),
                ('webseries_session_poster', models.ImageField(blank=True, null=True, upload_to='webseries_session_poster')),
                ('created_date', models.DateField(default=datetime.datetime(2020, 4, 16, 15, 45, 58, 204451))),
                ('webseries_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='NP_admin.main_catagory')),
            ],
        ),
    ]
