# Generated by Django 3.0.2 on 2020-04-16 15:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NP_admin', '0019_auto_20200416_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_content',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 16, 15, 56, 10, 465455)),
        ),
        migrations.AlterField(
            model_name='webseries_content',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 16, 15, 56, 10, 466545)),
        ),
        migrations.AlterField(
            model_name='webseries_season',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 16, 15, 56, 10, 467604)),
        ),
        migrations.AlterField(
            model_name='webseries_season',
            name='webseries_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='NP_admin.webseries_content'),
        ),
        migrations.CreateModel(
            name='webseries_season_episode',
            fields=[
                ('webseries_season_episode_id', models.AutoField(primary_key=True, serialize=False)),
                ('episode_name', models.CharField(max_length=100)),
                ('duration_hours', models.IntegerField()),
                ('duration_minutes', models.IntegerField()),
                ('release_date', models.DateField()),
                ('webseries_session_poster', models.ImageField(blank=True, null=True, upload_to='webseries_session_poster')),
                ('created_date', models.DateField(default=datetime.datetime(2020, 4, 16, 15, 56, 10, 468317))),
                ('webseries_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='NP_admin.webseries_content')),
                ('webseries_season_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='NP_admin.webseries_season')),
            ],
        ),
    ]
