# Generated by Django 3.0.2 on 2020-04-16 15:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NP_admin', '0020_auto_20200416_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webseries_content',
            name='episode',
        ),
        migrations.AlterField(
            model_name='movie_content',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 16, 15, 58, 3, 260640)),
        ),
        migrations.AlterField(
            model_name='webseries_content',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 16, 15, 58, 3, 261812)),
        ),
        migrations.AlterField(
            model_name='webseries_season',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 16, 15, 58, 3, 262895)),
        ),
        migrations.AlterField(
            model_name='webseries_season_episode',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 16, 15, 58, 3, 263585)),
        ),
    ]
