# Generated by Django 3.0.2 on 2020-04-16 16:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NP_admin', '0021_auto_20200416_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webseries_season',
            name='season_name',
        ),
        migrations.AddField(
            model_name='webseries_season_episode',
            name='episode',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie_content',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 16, 16, 14, 46, 44086)),
        ),
        migrations.AlterField(
            model_name='webseries_content',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 16, 16, 14, 46, 45158)),
        ),
        migrations.AlterField(
            model_name='webseries_season',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 16, 16, 14, 46, 46139)),
        ),
        migrations.AlterField(
            model_name='webseries_season_episode',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 16, 16, 14, 46, 46798)),
        ),
    ]
