# Generated by Django 3.0.2 on 2020-04-16 16:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NP_admin', '0022_auto_20200416_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webseries_content',
            name='webseries_1080p',
        ),
        migrations.RemoveField(
            model_name='webseries_content',
            name='webseries_576p',
        ),
        migrations.RemoveField(
            model_name='webseries_content',
            name='webseries_720p',
        ),
        migrations.RemoveField(
            model_name='webseries_content',
            name='webseries_episode_poster',
        ),
        migrations.RemoveField(
            model_name='webseries_content',
            name='webseries_thumbnail',
        ),
        migrations.RemoveField(
            model_name='webseries_content',
            name='webseries_trailer_1080p',
        ),
        migrations.RemoveField(
            model_name='webseries_content',
            name='webseries_trailer_576p',
        ),
        migrations.RemoveField(
            model_name='webseries_content',
            name='webseries_trailer_720p',
        ),
        migrations.RemoveField(
            model_name='webseries_content',
            name='webseries_trailer_thumbnail',
        ),
        migrations.RemoveField(
            model_name='webseries_season',
            name='webseries_session_poster',
        ),
        migrations.RemoveField(
            model_name='webseries_season_episode',
            name='webseries_session_poster',
        ),
        migrations.AddField(
            model_name='webseries_season',
            name='webseries_season_poster',
            field=models.ImageField(blank=True, null=True, upload_to='webseries_season_poster'),
        ),
        migrations.AddField(
            model_name='webseries_season',
            name='webseries_trailer_1080p',
            field=models.FileField(null=True, upload_to='webseries_trailers_1080p'),
        ),
        migrations.AddField(
            model_name='webseries_season',
            name='webseries_trailer_576p',
            field=models.FileField(null=True, upload_to='webseries_trailers_576p'),
        ),
        migrations.AddField(
            model_name='webseries_season',
            name='webseries_trailer_720p',
            field=models.FileField(null=True, upload_to='webseries_trailers_720p'),
        ),
        migrations.AddField(
            model_name='webseries_season',
            name='webseries_trailer_thumbnail',
            field=models.ImageField(null=True, upload_to='webseries_trailers_thumbnail'),
        ),
        migrations.AddField(
            model_name='webseries_season_episode',
            name='webseries_1080p',
            field=models.FileField(null=True, upload_to='webseries_1080p'),
        ),
        migrations.AddField(
            model_name='webseries_season_episode',
            name='webseries_576p',
            field=models.FileField(null=True, upload_to='webseries_576p'),
        ),
        migrations.AddField(
            model_name='webseries_season_episode',
            name='webseries_720p',
            field=models.FileField(null=True, upload_to='webseries_720p'),
        ),
        migrations.AddField(
            model_name='webseries_season_episode',
            name='webseries_season_poster',
            field=models.ImageField(blank=True, null=True, upload_to='webseries_season_poster'),
        ),
        migrations.AddField(
            model_name='webseries_season_episode',
            name='webseries_thumbnail',
            field=models.ImageField(null=True, upload_to='webseries_thumbnail'),
        ),
        migrations.AlterField(
            model_name='movie_content',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 16, 16, 39, 30, 8943)),
        ),
        migrations.AlterField(
            model_name='webseries_content',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 16, 16, 39, 30, 10008)),
        ),
        migrations.AlterField(
            model_name='webseries_season',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 16, 16, 39, 30, 10782)),
        ),
        migrations.AlterField(
            model_name='webseries_season_episode',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 16, 16, 39, 30, 11658)),
        ),
    ]
