# Generated by Django 3.0.2 on 2020-04-18 18:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NP_admin', '0024_auto_20200418_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='cast',
            name='cast_profile',
            field=models.ImageField(null=True, upload_to='cast_profile'),
        ),
        migrations.AddField(
            model_name='crew',
            name='crew_profile',
            field=models.ImageField(null=True, upload_to='crew_profile'),
        ),
        migrations.AlterField(
            model_name='movie_content',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 18, 18, 49, 35, 685917)),
        ),
        migrations.AlterField(
            model_name='webseries_content',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 18, 18, 49, 35, 686921)),
        ),
        migrations.AlterField(
            model_name='webseries_season',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 18, 18, 49, 35, 687675)),
        ),
        migrations.AlterField(
            model_name='webseries_season_episode',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 18, 18, 49, 35, 688491)),
        ),
    ]
