# Generated by Django 3.0.2 on 2020-04-19 10:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NP_admin', '0025_auto_20200418_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cast',
            name='movie',
        ),
        migrations.AddField(
            model_name='cast',
            name='movie',
            field=models.ManyToManyField(blank=True, null=True, to='NP_admin.movie_content'),
        ),
        migrations.RemoveField(
            model_name='cast',
            name='webseries',
        ),
        migrations.AddField(
            model_name='cast',
            name='webseries',
            field=models.ManyToManyField(blank=True, null=True, to='NP_admin.webseries_content'),
        ),
        migrations.AlterField(
            model_name='movie_content',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 19, 10, 21, 42, 11929)),
        ),
        migrations.AlterField(
            model_name='webseries_content',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 19, 10, 21, 42, 12922)),
        ),
        migrations.AlterField(
            model_name='webseries_season',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 19, 10, 21, 42, 13739)),
        ),
        migrations.AlterField(
            model_name='webseries_season_episode',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 19, 10, 21, 42, 14553)),
        ),
    ]
