# Generated by Django 3.0.2 on 2020-04-19 10:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NP_admin', '0026_auto_20200419_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cast',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='cast',
            name='webseries',
        ),
        migrations.RemoveField(
            model_name='crew',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='crew',
            name='webseries',
        ),
        migrations.AddField(
            model_name='movie_content',
            name='cast',
            field=models.ManyToManyField(blank=True, null=True, to='NP_admin.cast'),
        ),
        migrations.AlterField(
            model_name='movie_content',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 19, 10, 28, 31, 624323)),
        ),
        migrations.AlterField(
            model_name='webseries_content',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 19, 10, 28, 31, 626132)),
        ),
        migrations.AlterField(
            model_name='webseries_season',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 19, 10, 28, 31, 627090)),
        ),
        migrations.AlterField(
            model_name='webseries_season_episode',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 19, 10, 28, 31, 627930)),
        ),
    ]
