# Generated by Django 3.0.2 on 2020-04-19 11:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NP_admin', '0028_auto_20200419_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie_content',
            name='crew',
            field=models.ManyToManyField(blank=True, null=True, to='NP_admin.crew'),
        ),
        migrations.AlterField(
            model_name='movie_content',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 19, 11, 11, 23, 501309)),
        ),
        migrations.AlterField(
            model_name='webseries_content',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 19, 11, 11, 23, 504936)),
        ),
        migrations.AlterField(
            model_name='webseries_season',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 19, 11, 11, 23, 506299)),
        ),
        migrations.AlterField(
            model_name='webseries_season_episode',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 19, 11, 11, 23, 507598)),
        ),
    ]
