# Generated by Django 3.0.2 on 2020-04-19 11:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NP_admin', '0030_auto_20200419_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cast',
            name='about',
        ),
        migrations.RemoveField(
            model_name='cast',
            name='born_date',
        ),
        migrations.RemoveField(
            model_name='cast',
            name='born_nation',
        ),
        migrations.RemoveField(
            model_name='cast',
            name='born_place',
        ),
        migrations.RemoveField(
            model_name='cast',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='cast',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='cast',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='crew',
            name='about',
        ),
        migrations.RemoveField(
            model_name='crew',
            name='born_date',
        ),
        migrations.RemoveField(
            model_name='crew',
            name='born_nation',
        ),
        migrations.RemoveField(
            model_name='crew',
            name='born_place',
        ),
        migrations.RemoveField(
            model_name='crew',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='crew',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='crew',
            name='twitter',
        ),
        migrations.AlterField(
            model_name='movie_content',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 19, 11, 23, 51, 206486)),
        ),
        migrations.AlterField(
            model_name='webseries_content',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 19, 11, 23, 51, 208829)),
        ),
        migrations.AlterField(
            model_name='webseries_season',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 19, 11, 23, 51, 209756)),
        ),
        migrations.AlterField(
            model_name='webseries_season_episode',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 19, 11, 23, 51, 210657)),
        ),
    ]
