# Generated by Django 3.0.2 on 2020-04-19 18:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NP_admin', '0033_auto_20200419_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie_content',
            name='more_cast_crew_info',
        ),
        migrations.AddField(
            model_name='webseries_content',
            name='cast',
            field=models.ManyToManyField(blank=True, null=True, to='NP_admin.cast'),
        ),
        migrations.AddField(
            model_name='webseries_content',
            name='crew',
            field=models.ManyToManyField(blank=True, null=True, to='NP_admin.crew'),
        ),
        migrations.AlterField(
            model_name='movie_content',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 19, 18, 6, 44, 872681)),
        ),
        migrations.AlterField(
            model_name='webseries_content',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 19, 18, 6, 44, 874940)),
        ),
        migrations.AlterField(
            model_name='webseries_season',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 19, 18, 6, 44, 876729)),
        ),
        migrations.AlterField(
            model_name='webseries_season_episode',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 19, 18, 6, 44, 877682)),
        ),
    ]
