# Generated by Django 3.0.2 on 2020-04-19 22:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videosub', '0037_auto_20200419_2234'),
        ('NP_admin', '0035_auto_20200419_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_content',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 19, 22, 34, 43, 680212)),
        ),
        migrations.AlterField(
            model_name='webseries_content',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 19, 22, 34, 43, 682499)),
        ),
        migrations.AlterField(
            model_name='webseries_season',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 19, 22, 34, 43, 684474)),
        ),
        migrations.AlterField(
            model_name='webseries_season_episode',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 19, 22, 34, 43, 686392)),
        ),
        migrations.CreateModel(
            name='mywatchlist',
            fields=[
                ('watchlist_id', models.AutoField(primary_key=True, serialize=False)),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='videosub.member_record')),
                ('movies', models.ManyToManyField(null=True, to='NP_admin.movie_content')),
                ('webseries', models.ManyToManyField(null=True, to='NP_admin.webseries_content')),
            ],
        ),
    ]
