# Generated by Django 3.0.2 on 2020-04-21 10:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videosub', '0038_auto_20200421_1040'),
        ('NP_admin', '0036_auto_20200419_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_content',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 21, 10, 40, 3, 406184)),
        ),
        migrations.AlterField(
            model_name='mywatchlist',
            name='movies',
            field=models.ManyToManyField(blank=True, null=True, to='NP_admin.movie_content'),
        ),
        migrations.AlterField(
            model_name='mywatchlist',
            name='webseries',
            field=models.ManyToManyField(blank=True, null=True, to='NP_admin.webseries_content'),
        ),
        migrations.AlterField(
            model_name='webseries_content',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 21, 10, 40, 3, 408444)),
        ),
        migrations.AlterField(
            model_name='webseries_season',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 21, 10, 40, 3, 410334)),
        ),
        migrations.AlterField(
            model_name='webseries_season_episode',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 21, 10, 40, 3, 411182)),
        ),
        migrations.CreateModel(
            name='movie_review',
            fields=[
                ('movie_review_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField(max_length=1000)),
                ('rating', models.FloatField(default=0)),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='videosub.member_record')),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='NP_admin.movie_content')),
            ],
        ),
    ]
