# Generated by Django 3.0.2 on 2020-04-21 10:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NP_admin', '0037_auto_20200421_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_content',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 21, 10, 41, 44, 337896)),
        ),
        migrations.AlterField(
            model_name='movie_content',
            name='description',
            field=models.TextField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='webseries_content',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 21, 10, 41, 44, 340097)),
        ),
        migrations.AlterField(
            model_name='webseries_content',
            name='description',
            field=models.TextField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='webseries_season',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 21, 10, 41, 44, 342012)),
        ),
        migrations.AlterField(
            model_name='webseries_season_episode',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 21, 10, 41, 44, 342980)),
        ),
    ]
