# Generated by Django 3.0.2 on 2020-04-22 12:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videosub', '0041_auto_20200422_1208'),
        ('NP_admin', '0039_auto_20200421_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='movies_watchlist',
            fields=[
                ('movies_watchlist_id', models.AutoField(primary_key=True, serialize=False)),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='videosub.member_record')),
            ],
        ),
        migrations.AlterField(
            model_name='movie_content',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 22, 12, 8, 12, 122806)),
        ),
        migrations.AlterField(
            model_name='movie_review',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 22, 12, 8, 12, 130359)),
        ),
        migrations.AlterField(
            model_name='webseries_content',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 22, 12, 8, 12, 125093)),
        ),
        migrations.AlterField(
            model_name='webseries_season',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 22, 12, 8, 12, 127260)),
        ),
        migrations.AlterField(
            model_name='webseries_season_episode',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 22, 12, 8, 12, 128928)),
        ),
        migrations.DeleteModel(
            name='mywatchlist',
        ),
        migrations.AddField(
            model_name='movies_watchlist',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='NP_admin.movie_content'),
        ),
    ]
