# Generated by Django 3.0.2 on 2020-04-22 13:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NP_admin', '0041_auto_20200422_1250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies_watchlist',
            old_name='movie_review',
            new_name='movie_rating',
        ),
        migrations.AlterField(
            model_name='movie_content',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 22, 13, 3, 4, 812407)),
        ),
        migrations.AlterField(
            model_name='movie_review',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 22, 13, 3, 4, 819844)),
        ),
        migrations.AlterField(
            model_name='webseries_content',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 22, 13, 3, 4, 814883)),
        ),
        migrations.AlterField(
            model_name='webseries_season',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 22, 13, 3, 4, 817690)),
        ),
        migrations.AlterField(
            model_name='webseries_season_episode',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 22, 13, 3, 4, 819011)),
        ),
    ]
