# Generated by Django 3.0.2 on 2020-04-23 02:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NP_admin', '0046_auto_20200423_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_content',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 23, 2, 54, 39, 498587)),
        ),
        migrations.AlterField(
            model_name='movie_review',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 23, 2, 54, 39, 504485)),
        ),
        migrations.AlterField(
            model_name='movies_watchlist',
            name='movie_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='webseries_content',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 23, 2, 54, 39, 500915)),
        ),
        migrations.AlterField(
            model_name='webseries_season',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 23, 2, 54, 39, 502882)),
        ),
        migrations.AlterField(
            model_name='webseries_season_episode',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 23, 2, 54, 39, 503780)),
        ),
    ]
