# Generated by Django 3.0.2 on 2020-04-23 09:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NP_admin', '0047_auto_20200423_0254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies_watchlist',
            name='movie_rating',
        ),
        migrations.AlterField(
            model_name='movie_content',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 23, 9, 52, 49, 988773)),
        ),
        migrations.AlterField(
            model_name='movie_review',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 23, 9, 52, 49, 994363)),
        ),
        migrations.AlterField(
            model_name='webseries_content',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 23, 9, 52, 49, 991044)),
        ),
        migrations.AlterField(
            model_name='webseries_season',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 23, 9, 52, 49, 992831)),
        ),
        migrations.AlterField(
            model_name='webseries_season_episode',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 23, 9, 52, 49, 993674)),
        ),
    ]
