# Generated by Django 3.0.2 on 2020-04-23 10:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videosub', '0050_auto_20200423_1011'),
        ('NP_admin', '0048_auto_20200423_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='webseries_content',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='movie_content',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 23, 10, 11, 14, 866804)),
        ),
        migrations.AlterField(
            model_name='movie_review',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 23, 10, 11, 14, 872520)),
        ),
        migrations.AlterField(
            model_name='webseries_content',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 23, 10, 11, 14, 869027)),
        ),
        migrations.AlterField(
            model_name='webseries_season',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 23, 10, 11, 14, 870900)),
        ),
        migrations.AlterField(
            model_name='webseries_season_episode',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 23, 10, 11, 14, 871752)),
        ),
        migrations.CreateModel(
            name='webseries_watchlist',
            fields=[
                ('webseries_watchlist_id', models.AutoField(primary_key=True, serialize=False)),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='videosub.member_record')),
                ('webseries', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='NP_admin.webseries_content')),
            ],
        ),
        migrations.CreateModel(
            name='webseries_review',
            fields=[
                ('webseries_review_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField(max_length=1000)),
                ('rating', models.FloatField(default=0)),
                ('created_date', models.DateField(default=datetime.datetime(2020, 4, 23, 10, 11, 14, 873339))),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='videosub.member_record')),
                ('webseries', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='NP_admin.webseries_content')),
            ],
        ),
    ]
