# Generated by Django 3.0.2 on 2020-04-23 15:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NP_admin', '0049_auto_20200423_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_catagory',
            name='main_catagory',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='movie_content',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 23, 15, 28, 37, 560685)),
        ),
        migrations.AlterField(
            model_name='movie_review',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 23, 15, 28, 37, 566489)),
        ),
        migrations.AlterField(
            model_name='sub_catagory',
            name='main_catagory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='NP_admin.main_catagory'),
        ),
        migrations.AlterField(
            model_name='sub_catagory',
            name='sub_catagory',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='type_catagory',
            name='main_catagory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='NP_admin.main_catagory'),
        ),
        migrations.AlterField(
            model_name='type_catagory',
            name='sub_catagory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='NP_admin.sub_catagory'),
        ),
        migrations.AlterField(
            model_name='type_catagory',
            name='type_catagory',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='webseries_content',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 23, 15, 28, 37, 562999)),
        ),
        migrations.AlterField(
            model_name='webseries_review',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 23, 15, 28, 37, 567343)),
        ),
        migrations.AlterField(
            model_name='webseries_season',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 23, 15, 28, 37, 564879)),
        ),
        migrations.AlterField(
            model_name='webseries_season_episode',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 23, 15, 28, 37, 565791)),
        ),
    ]
