# Generated by Django 3.0.2 on 2020-04-24 19:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NP_admin', '0050_auto_20200423_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie_content',
            name='movie_1080p',
        ),
        migrations.RemoveField(
            model_name='movie_content',
            name='movie_576p',
        ),
        migrations.RemoveField(
            model_name='movie_content',
            name='movie_trailer_1080p',
        ),
        migrations.RemoveField(
            model_name='movie_content',
            name='movie_trailer_576p',
        ),
        migrations.RemoveField(
            model_name='webseries_season',
            name='webseries_trailer_1080p',
        ),
        migrations.RemoveField(
            model_name='webseries_season',
            name='webseries_trailer_576p',
        ),
        migrations.RemoveField(
            model_name='webseries_season_episode',
            name='webseries_1080p',
        ),
        migrations.RemoveField(
            model_name='webseries_season_episode',
            name='webseries_576p',
        ),
        migrations.AlterField(
            model_name='movie_content',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 24, 19, 48, 6, 363956)),
        ),
        migrations.AlterField(
            model_name='movie_review',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 24, 19, 48, 6, 370227)),
        ),
        migrations.AlterField(
            model_name='webseries_content',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 24, 19, 48, 6, 366490)),
        ),
        migrations.AlterField(
            model_name='webseries_review',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 24, 19, 48, 6, 371119)),
        ),
        migrations.AlterField(
            model_name='webseries_season',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 24, 19, 48, 6, 368635)),
        ),
        migrations.AlterField(
            model_name='webseries_season_episode',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 24, 19, 48, 6, 369531)),
        ),
    ]
