# Generated by Django 3.0.2 on 2020-04-28 10:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NP_admin', '0062_auto_20200427_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_catagory',
            name='main_cat_image',
            field=models.ImageField(blank=True, null=True, upload_to='main_cat_image'),
        ),
        migrations.AlterField(
            model_name='movie_content',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 28, 10, 16, 26, 667160)),
        ),
        migrations.AlterField(
            model_name='movie_review',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 28, 10, 16, 26, 676366)),
        ),
        migrations.AlterField(
            model_name='webseries_content',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 28, 10, 16, 26, 671739)),
        ),
        migrations.AlterField(
            model_name='webseries_review',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 28, 10, 16, 26, 677408)),
        ),
        migrations.AlterField(
            model_name='webseries_season',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 28, 10, 16, 26, 674680)),
        ),
        migrations.AlterField(
            model_name='webseries_season_episode',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 28, 10, 16, 26, 675555)),
        ),
    ]
