# Generated by Django 3.0.2 on 2020-04-28 10:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NP_admin', '0063_auto_20200428_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_content',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 28, 10, 32, 31, 188654)),
        ),
        migrations.AlterField(
            model_name='movie_content',
            name='movie_trailer_720p',
            field=models.FileField(max_length=200, null=True, upload_to='movie_trailers_720p'),
        ),
        migrations.AlterField(
            model_name='movie_content',
            name='movie_trailer_thumbnail',
            field=models.ImageField(max_length=200, null=True, upload_to='movie_trailers_thumbnail'),
        ),
        migrations.AlterField(
            model_name='movie_review',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 28, 10, 32, 31, 194407)),
        ),
        migrations.AlterField(
            model_name='webseries_content',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 28, 10, 32, 31, 190914)),
        ),
        migrations.AlterField(
            model_name='webseries_review',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 28, 10, 32, 31, 195312)),
        ),
        migrations.AlterField(
            model_name='webseries_season',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 28, 10, 32, 31, 192963)),
        ),
        migrations.AlterField(
            model_name='webseries_season_episode',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 28, 10, 32, 31, 193673)),
        ),
    ]
