# Generated by Django 3.0.2 on 2020-04-29 11:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NP_admin', '0064_auto_20200428_1032'),
    ]

    operations = [
        migrations.CreateModel(
            name='language',
            fields=[
                ('language_id', models.AutoField(primary_key=True, serialize=False)),
                ('language', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='movie_content',
            name='movie_720p',
        ),
        migrations.RemoveField(
            model_name='movie_content',
            name='movie_thumbnail',
        ),
        migrations.RemoveField(
            model_name='movie_content',
            name='movie_trailer_720p',
        ),
        migrations.RemoveField(
            model_name='movie_content',
            name='movie_trailer_thumbnail',
        ),
        migrations.AlterField(
            model_name='movie_content',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 29, 11, 6, 52, 558121)),
        ),
        migrations.AlterField(
            model_name='movie_review',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 29, 11, 6, 52, 564648)),
        ),
        migrations.AlterField(
            model_name='webseries_content',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 29, 11, 6, 52, 561234)),
        ),
        migrations.AlterField(
            model_name='webseries_review',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 29, 11, 6, 52, 565557)),
        ),
        migrations.AlterField(
            model_name='webseries_season',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 29, 11, 6, 52, 563255)),
        ),
        migrations.AlterField(
            model_name='webseries_season_episode',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 29, 11, 6, 52, 563969)),
        ),
        migrations.CreateModel(
            name='multiple_audio_movies',
            fields=[
                ('multiple_audio_movies_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('movie_trailer_thumbnail', models.ImageField(max_length=200, null=True, upload_to='movie_trailers_thumbnail')),
                ('movie_trailer_720p', models.FileField(max_length=200, null=True, upload_to='movie_trailers_720p')),
                ('movie_thumbnail', models.ImageField(null=True, upload_to='movie_thumbnail')),
                ('movie_720p', models.FileField(null=True, upload_to='movie_720p')),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='NP_admin.language')),
                ('movie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='NP_admin.movie_content')),
            ],
        ),
    ]
