# Generated by Django 3.0.2 on 2020-04-29 11:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NP_admin', '0065_auto_20200429_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multiple_audio_movies',
            name='movie_trailer_720p',
        ),
        migrations.RemoveField(
            model_name='multiple_audio_movies',
            name='movie_trailer_thumbnail',
        ),
        migrations.AddField(
            model_name='movie_content',
            name='movie_trailer_720p',
            field=models.FileField(max_length=200, null=True, upload_to='movie_trailers_720p'),
        ),
        migrations.AddField(
            model_name='movie_content',
            name='movie_trailer_thumbnail',
            field=models.ImageField(max_length=200, null=True, upload_to='movie_trailers_thumbnail'),
        ),
        migrations.AlterField(
            model_name='movie_content',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 29, 11, 12, 47, 144266)),
        ),
        migrations.AlterField(
            model_name='movie_review',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 29, 11, 12, 47, 150799)),
        ),
        migrations.AlterField(
            model_name='webseries_content',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 29, 11, 12, 47, 147334)),
        ),
        migrations.AlterField(
            model_name='webseries_review',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 29, 11, 12, 47, 151629)),
        ),
        migrations.AlterField(
            model_name='webseries_season',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 29, 11, 12, 47, 149259)),
        ),
        migrations.AlterField(
            model_name='webseries_season_episode',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 29, 11, 12, 47, 149968)),
        ),
    ]
