# Generated by Django 3.0.2 on 2020-05-04 11:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NP_admin', '0068_auto_20200504_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webseries_content',
            name='duration_hours',
        ),
        migrations.RemoveField(
            model_name='webseries_content',
            name='duration_minutes',
        ),
        migrations.AlterField(
            model_name='movie_content',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 5, 4, 11, 56, 54, 766666)),
        ),
        migrations.AlterField(
            model_name='movie_review',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 5, 4, 11, 56, 54, 773048)),
        ),
        migrations.AlterField(
            model_name='webseries_content',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 5, 4, 11, 56, 54, 769653)),
        ),
        migrations.AlterField(
            model_name='webseries_review',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 5, 4, 11, 56, 54, 773870)),
        ),
        migrations.AlterField(
            model_name='webseries_season',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 5, 4, 11, 56, 54, 771475)),
        ),
        migrations.AlterField(
            model_name='webseries_season_episode',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 5, 4, 11, 56, 54, 772331)),
        ),
    ]
