# Generated by Django 3.0.2 on 2020-05-04 12:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NP_admin', '0069_auto_20200504_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webseries_season',
            name='webseries_season_poster',
        ),
        migrations.RemoveField(
            model_name='webseries_season_episode',
            name='webseries_season_poster',
        ),
        migrations.AlterField(
            model_name='movie_content',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 5, 4, 12, 43, 34, 38835)),
        ),
        migrations.AlterField(
            model_name='movie_review',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 5, 4, 12, 43, 34, 45180)),
        ),
        migrations.AlterField(
            model_name='webseries_content',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 5, 4, 12, 43, 34, 41922)),
        ),
        migrations.AlterField(
            model_name='webseries_review',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 5, 4, 12, 43, 34, 46008)),
        ),
        migrations.AlterField(
            model_name='webseries_season',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 5, 4, 12, 43, 34, 43721)),
        ),
        migrations.AlterField(
            model_name='webseries_season_episode',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 5, 4, 12, 43, 34, 44512)),
        ),
    ]
