# Generated by Django 3.0.2 on 2020-05-17 14:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NP_admin', '0071_auto_20200505_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='movie_download_link',
            fields=[
                ('movie_download_link_id', models.AutoField(primary_key=True, serialize=False)),
                ('movie_name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1500)),
            ],
        ),
        migrations.AlterField(
            model_name='movie_content',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 5, 17, 14, 11, 23, 692495)),
        ),
        migrations.AlterField(
            model_name='movie_review',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 5, 17, 14, 11, 23, 700200)),
        ),
        migrations.AlterField(
            model_name='webseries_content',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 5, 17, 14, 11, 23, 695485)),
        ),
        migrations.AlterField(
            model_name='webseries_review',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 5, 17, 14, 11, 23, 701130)),
        ),
        migrations.AlterField(
            model_name='webseries_season',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 5, 17, 14, 11, 23, 698410)),
        ),
        migrations.AlterField(
            model_name='webseries_season_episode',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 5, 17, 14, 11, 23, 699184)),
        ),
    ]
