# Generated by Django 3.0.2 on 2020-05-17 14:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NP_admin', '0072_auto_20200517_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='webseries_download_link',
            fields=[
                ('webseries_download_link_id', models.AutoField(primary_key=True, serialize=False)),
                ('webseries_name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1500)),
                ('webseries_poster', models.ImageField(blank=True, null=True, upload_to='webseries_poster')),
            ],
        ),
        migrations.AddField(
            model_name='movie_download_link',
            name='movie_poster',
            field=models.ImageField(blank=True, null=True, upload_to='movie_poster'),
        ),
        migrations.AlterField(
            model_name='movie_content',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 5, 17, 14, 15, 15, 821572)),
        ),
        migrations.AlterField(
            model_name='movie_review',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 5, 17, 14, 15, 15, 830229)),
        ),
        migrations.AlterField(
            model_name='webseries_content',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 5, 17, 14, 15, 15, 824981)),
        ),
        migrations.AlterField(
            model_name='webseries_review',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 5, 17, 14, 15, 15, 831143)),
        ),
        migrations.AlterField(
            model_name='webseries_season',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 5, 17, 14, 15, 15, 828027)),
        ),
        migrations.AlterField(
            model_name='webseries_season_episode',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 5, 17, 14, 15, 15, 828758)),
        ),
    ]
