# Generated by Django 3.0.2 on 2020-05-17 14:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NP_admin', '0074_auto_20200517_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie_download_link',
            name='link',
        ),
        migrations.RemoveField(
            model_name='webseries_download_link',
            name='link',
        ),
        migrations.AddField(
            model_name='movie_download_link',
            name='link1080p',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='movie_download_link',
            name='link480p',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='movie_download_link',
            name='link720p',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='webseries_download_link',
            name='link1080p',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='webseries_download_link',
            name='link480p',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='webseries_download_link',
            name='link720p',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='movie_content',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 5, 17, 14, 44, 39, 803857)),
        ),
        migrations.AlterField(
            model_name='movie_review',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 5, 17, 14, 44, 39, 813496)),
        ),
        migrations.AlterField(
            model_name='webseries_content',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 5, 17, 14, 44, 39, 807024)),
        ),
        migrations.AlterField(
            model_name='webseries_review',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 5, 17, 14, 44, 39, 814456)),
        ),
        migrations.AlterField(
            model_name='webseries_season',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 5, 17, 14, 44, 39, 811101)),
        ),
        migrations.AlterField(
            model_name='webseries_season_episode',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 5, 17, 14, 44, 39, 811866)),
        ),
    ]
