# Generated by Django 3.0.2 on 2020-05-19 07:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NP_admin', '0075_auto_20200517_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie_download_link',
            name='link1080p',
        ),
        migrations.RemoveField(
            model_name='movie_download_link',
            name='link480p',
        ),
        migrations.RemoveField(
            model_name='movie_download_link',
            name='link720p',
        ),
        migrations.RemoveField(
            model_name='webseries_download_link',
            name='link1080p',
        ),
        migrations.RemoveField(
            model_name='webseries_download_link',
            name='link480p',
        ),
        migrations.RemoveField(
            model_name='webseries_download_link',
            name='link720p',
        ),
        migrations.AlterField(
            model_name='movie_content',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 5, 19, 7, 32, 35, 162666)),
        ),
        migrations.AlterField(
            model_name='movie_review',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 5, 19, 7, 32, 35, 172273)),
        ),
        migrations.AlterField(
            model_name='webseries_content',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 5, 19, 7, 32, 35, 166253)),
        ),
        migrations.AlterField(
            model_name='webseries_review',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 5, 19, 7, 32, 35, 173176)),
        ),
        migrations.AlterField(
            model_name='webseries_season',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 5, 19, 7, 32, 35, 170016)),
        ),
        migrations.AlterField(
            model_name='webseries_season_episode',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 5, 19, 7, 32, 35, 170860)),
        ),
    ]
